/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVIDOR_IDS_H_RPCGEN
#define _SERVIDOR_IDS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct retorno {
	int cod_ret;
	union {
		int id;
		char msj_error[800];
	} retorno_u;
};
typedef struct retorno retorno;

#define SERVIDOR_IDS_PROG 0x20000099
#define SERVIDOR_IDS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define OBTENER_NUEVO_ID_SOCIO 1
extern  retorno * obtener_nuevo_id_socio_1(void *, CLIENT *);
extern  retorno * obtener_nuevo_id_socio_1_svc(void *, struct svc_req *);
#define DEVOLVER_ID_SOCIO 2
extern  retorno * devolver_id_socio_1(int *, CLIENT *);
extern  retorno * devolver_id_socio_1_svc(int *, struct svc_req *);
#define OBTENER_NUEVO_ID_PUERTA 3
extern  retorno * obtener_nuevo_id_puerta_1(void *, CLIENT *);
extern  retorno * obtener_nuevo_id_puerta_1_svc(void *, struct svc_req *);
#define DEVOLVER_ID_PUERTA 4
extern  retorno * devolver_id_puerta_1(int *, CLIENT *);
extern  retorno * devolver_id_puerta_1_svc(int *, struct svc_req *);
#define OBTENER_NUEVO_ID_BUS 5
extern  retorno * obtener_nuevo_id_bus_1(void *, CLIENT *);
extern  retorno * obtener_nuevo_id_bus_1_svc(void *, struct svc_req *);
#define DEVOLVER_ID_BUS 6
extern  retorno * devolver_id_bus_1(int *, CLIENT *);
extern  retorno * devolver_id_bus_1_svc(int *, struct svc_req *);
extern int servidor_ids_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OBTENER_NUEVO_ID_SOCIO 1
extern  retorno * obtener_nuevo_id_socio_1();
extern  retorno * obtener_nuevo_id_socio_1_svc();
#define DEVOLVER_ID_SOCIO 2
extern  retorno * devolver_id_socio_1();
extern  retorno * devolver_id_socio_1_svc();
#define OBTENER_NUEVO_ID_PUERTA 3
extern  retorno * obtener_nuevo_id_puerta_1();
extern  retorno * obtener_nuevo_id_puerta_1_svc();
#define DEVOLVER_ID_PUERTA 4
extern  retorno * devolver_id_puerta_1();
extern  retorno * devolver_id_puerta_1_svc();
#define OBTENER_NUEVO_ID_BUS 5
extern  retorno * obtener_nuevo_id_bus_1();
extern  retorno * obtener_nuevo_id_bus_1_svc();
#define DEVOLVER_ID_BUS 6
extern  retorno * devolver_id_bus_1();
extern  retorno * devolver_id_bus_1_svc();
extern int servidor_ids_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_retorno (XDR *, retorno*);

#else /* K&R C */
extern bool_t xdr_retorno ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVIDOR_IDS_H_RPCGEN */
