/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "servidor_ids.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

retorno *
obtener_nuevo_id_socio_1(void *argp, CLIENT *clnt)
{
	static retorno clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OBTENER_NUEVO_ID_SOCIO,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_retorno, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

retorno *
devolver_id_socio_1(int *argp, CLIENT *clnt)
{
	static retorno clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DEVOLVER_ID_SOCIO,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_retorno, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

retorno *
obtener_nuevo_id_puerta_1(void *argp, CLIENT *clnt)
{
	static retorno clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OBTENER_NUEVO_ID_PUERTA,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_retorno, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

retorno *
devolver_id_puerta_1(int *argp, CLIENT *clnt)
{
	static retorno clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DEVOLVER_ID_PUERTA,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_retorno, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

retorno *
obtener_nuevo_id_bus_1(void *argp, CLIENT *clnt)
{
	static retorno clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OBTENER_NUEVO_ID_BUS,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_retorno, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

retorno *
devolver_id_bus_1(int *argp, CLIENT *clnt)
{
	static retorno clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DEVOLVER_ID_BUS,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_retorno, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
